changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 💥
      labels:
        - breaking changes
    - title: New Features ✨
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - bugfix
    - title: Improvements ⚡️
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - breaking changes
          - feature
          - bugfix
          - enhancement
