apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}-backup
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  {{- with .Values.backup.pvc.class }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - {{ .Values.backup.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.backup.pvc.dataSize }}
