{{- if not (.Values.env.existingSecret) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dashy.fullname" . }}-env
  labels:
    {{- include "dashy.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
