{{- if .Values.static.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dashy.fullname" . }}
  labels:
    {{- include "dashy.labels" . | nindent 4 }}
data:
  {{- toJson .Values.static.configMapContent | nindent 2 }}
{{- end -}}
