apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dashy.fullname" . }}
  labels:
    {{- include "dashy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.strategyType | default "Recreate" }}
  selector:
    matchLabels:
      {{- include "dashy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dashy.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dashy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env}}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          startupProbe:
            exec:
              command:
                - yarn
                - health-check
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 90
            initialDelaySeconds: 40
          livenessProbe:
            exec:
              command:
                - yarn
                - health-check
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 90
          readinessProbe:
            httpGet:
              port: 80
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 90
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{ if .Values.static.enabled }}
            - mountPath: /app/public/conf.yml
              subPath: conf.yml
              name: dashy-conf
            {{ end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{ if and (.Values.static.enabled) (not .Values.static.secret) }}
        - name: dashy-conf
          configMap:
            name: dashy
            items:
              - key: conf
                path: conf.yml
        {{ else if and (.Values.static.enabled) (.Values.static.secret) }}
        - name: dashy-conf
          secret:
            secretName: dashy
            items:
              - key: conf
                path: conf.yml
        {{ end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
