{{- if and (.Values.static.enabled) (.Values.static.secret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dashy.fullname" . }}
  labels:
    {{- include "dashy.labels" . | nindent 4 }}
stringData:
  {{- toJson .Values.static.configMapContent | nindent 2 }}
{{- end -}}
