apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bazarr.fullname" . }}
  labels:
    {{- include "bazarr.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: {{ .Values.strategyType | default "Recreate" }}
  selector:
    matchLabels:
      {{- include "bazarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bazarr.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bazarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "bazarr.fullname" . }}-env
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 90
            initialDelaySeconds: 40
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 90
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 90
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: {{ include "bazarr.fullname" . }}-conf
            - mountPath: /media
              name: {{ include "bazarr.fullname" . }}-media
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "bazarr.fullname" . }}-conf
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-config" (include "bazarr.fullname" .)) .Values.storage.config.existingClaim }}
        - name: {{ include "bazarr.fullname" . }}-media
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-media" (include "bazarr.fullname" .)) .Values.storage.media.existingClaim }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
