apiVersion: v2
name: firefly-iii-stack
version: 0.1.0
description: Installs Firefly III stack (db, app, importer)
type: application
dependencies:
  - name: postgres
    version: 0.1.0
    condition: postgres.enabled
    repository: https://vyrtualsynthese.github.io/selfhosted-helmcharts/
  - name: firefly-iii
    version: 1.7.2
    condition: firefly-iii.enabled
    repository: https://firefly-iii.github.io/kubernetes/
  - name: importer
    version: 1.3.1
    condition: importer.enabled
    repository: https://firefly-iii.github.io/kubernetes/
