apiVersion: v1
kind: Service
metadata:
  name: {{ include "calibre.fullname" . }}
  labels:
    {{- include "calibre.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.gui.port }}
      targetPort: gui
      protocol: TCP
      name: gui
    - port: {{ .Values.service.webui.port }}
      targetPort: webui
      protocol: TCP
      name: webui
  selector:
    {{- include "calibre.selectorLabels" . | nindent 4 }}
